### PR TITLE
Swift4.2

### PR DESCRIPTION
**Pull request by quinnthomson**
## How to test
1. Build in Xcode 9
2. Build in Xcode 10
Dance with joy as both builds succeed 🎉 

## Areas of the app affected
I've added compiler `#if`s so that Astro will compile for Swift 4.2 as well as previous versions.

## Changelog
- Make Astro work with Swift 4.2

### CODE REVIEW

**Comment by quinnthomson** [comment]
Note: GitHub is slow right now, so this PR may not have all 4 commits yet...

**Comment by interstateone** [comment]
Nice, thanks Quinn. Two questions:

1) Do we need to support Swift before 4.2 if we're also bumping the minor version here? That might simplify the code for 4.2 and we could always release a 4.1.x version for fixes that support < 4.2. I don't have strong opinions about this since we don't release things that often.
2) If we do support both: Since the Swift APIs before and after 4.2 are _so similar_, I'm wondering how you feel about using some shim code to unify the API instead of `#if`s. I found this makes the call site nicer and makes it clear that this is shim code and that the behaviour should be the same between the two versions of it. Something like:
```
#if swift(>=4.2)
#else
extension UIViewController {	
    public var children: [UIViewController] {	
        return childViewControllers	
    }	
     public func addChild(_ child: UIViewController) {	
        addChildViewController(child)	
    }
    // etc.
}
#endif

public func addChildViewController(_ childViewController: UIViewController, inContainer view: UIView) {
         self.addChild(childViewController)
         view.addSubview(childViewController.view)
         childViewController.didMove(toParent: self)
}
```

**Comment by interstateone** [comment]
Oh, also I think the version number you want to bump is [this one](https://github.com/RobotsAndPencils/Astro/blob/master/Astro.podspec#L11) if that's the intent. I have a feeling that the one in the Info.plist is only used in the Xcode project we use for development, not for end users.

**Comment by quinnthomson** [comment]
I vote that we should use 4.2 only, and not worry about supporting multiple Swift versions. People should just point at an earlier release if they’re not updating. Thoughts?

**Comment by paulthorsteinson** [comment]
Gonna merge this?  Its the only pod in my pod file left to upgrade to 4.2

**Comment by interstateone** [comment]
@quinnthomson Are you able to make that change to only support 4.2 instead of having both versions of code?

**Comment by quinnthomson** [comment]
@paulthorsteinson review and merge!
@interstateone done!

**Comment by paulthorsteinson** [comment]
Thanks!

**Pull request merged**
