### PR TITLE
Swift 4 support. Updates pods. Xcode 9 updates

### PR DESCRIPTION
**Pull request by MattKiazyk**
## Summary

This will update the project to support Xcode 9, as well as convert to Swift 4

### CODE REVIEW

**Comment by csykes** [comment]
So what version number should we advance Astro to? Its at 4.1.0 now... 
I was thinking 4.1.1 or 5.0.0 depending on how we view backwards compatibility

**Comment by MattKiazyk** [comment]
Would not 4.1.1 get updated automatically if users had pod Astro, -> '4.1` - i'm not sure we want that?
I'm ok with either 4.2 or 5.0

**Comment by csykes** [comment]
Even a 4.2 would get picked up by a Swift3 project in most cases... I'm leaning towards 5.0
I wonder what version numbers the other Swift 4 pod migrations moved up?

**Comment by MattKiazyk** [comment]
Lets go with 5.0 then! 👍

**Pull request merged**
